# Generated by Django 3.1 on 2020-08-29 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='color',
        ),
    ]
