# Generated by Django 3.1 on 2020-08-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0002_remove_todo_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
